service: cors-proxy-sroop

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 60
  stage: dev
  region: us-west-1
  environment:
    foo: 123

functions:
  lambda:
    name: cors-proxy
    handler: handler.corsProxy
    events:
      - http:
          path: ''
          method: get
          cors: true